package Daje::Workflow::Workflow;
use Mojo::Base -base, -signatures;

use Daje::Workflow::Loader;
use Daje::Workflow::Database;

# NAME
# ====
#
# Daje::Workflow - It's new $module
#
# SYNOPSIS
# ========
#
#    use Daje::Workflow;
#
#
# DESCRIPTION
# ===========
# Daje::Workflow is ...
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
# janeskil1525 E<lt>janeskil1525@gmail.comE<gt>
#

our $VERSION = "0.01";

has 'config';
has 'workflow';
has 'workflow_pkey';
has 'context';
has 'loader';
has 'database';
has 'db';
has 'pg';

sub process($self) {

    $self->_db_connection();
    unless ($self->error()->exists()){
        $self->db($self->pg->db);
        my $tx = $self->db->begin();
        if ($self->_init()) {


        }
    }

}

sub _db_connection($self) {
    eval {
        my $pg = Mojo::Pg->new()->dsn(
            "dbi:Pg:dbname=Workflowtest;host=database;port=54321;user=test;password=test"
        );
        $self-pg($pg);
    };
    if (defined $@) {
        $self->error()->add($@);
    }
}

sub _init($self) {

    eval {
        my $loader = Daje::Workflow::Loader->new(
            path => $self->context->{config_path}
        )->load();
        $self->loader($loader);



        my $db = $pg->db;
        my $tx = $db->begin();
        my $database = Daje::Workflow::Database->new(
            pg            => $pg,
            db            => $db,
            workflow      => $self->worlflow,
            workflow_pkey => $self->worlflow_pkey,
            context       => $self->context,
        );
        $self->database($database);
        $self->database->start();

    };
    $self->error()->add($@) if defined $@;
}

1;
__END__




#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Workflow - It's new $module



=head1 SYNOPSIS


   use Daje::Workflow;




=head1 DESCRIPTION

Daje::Workflow is ...



=head1 REQUIRES

L<Mojo::Base> 


=head1 METHODS

=head2 process($self,

 process($self,();


=head1 AUTHOR

janeskil1525 E<lt>janeskil1525@gmail.comE<gt>



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

